version: "3"
services: 
  app:
    build: ./app
    container_name: php-app
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "8000:80"
    depends_on: 
      - db
  db:
    build: ./db
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
      - MYSQL_USER=php_user
      - MYSQL_PASSWORD=php_pass
    ports:
      - "3306:3306"
    container_name: php-db